version: '3.8'

services:
  phils-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: phils-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
